
asset:
  - 'EURUSD=X'
  - 'GBPUSD=X'
  - 'USDJPY=X'
  - 'USDCHF=X'
  - 'AUDUSD=X'
  - 'NZDUSD=X'
  - 'USDCAD=X'
  - 'EURGBP=X'
  - 'EURJPY=X'
  - 'EURCHF=X'
  - 'EURAUD=X'
  - 'EURNZD=X'
  - 'EURCAD=X'
  - 'GBPJPY=X'
  - 'GBPCHF=X'
  - 'GBPAUD=X'
  - 'GBPNZD=X'
  - 'GBPCAD=X'
  - 'CHFJPY=X'
  - 'AUDJPY=X'
  - 'AUDCHF=X'
  - 'AUDNZD=X'
  - 'AUDCAD=X'
  - 'NZDJPY=X'
  - 'NZDCHF=X'
  - 'NZDCAD=X'
  - 'CADJPY=X'
  - 'CADCHF=X'
#  - 'XAGUSD=X'
#  - 'XAUUSD=X'
#  - 'XBRUSD=X'
#  - 'XTIUSD=X'
#  - 'AUS200=X'
#  - 'UK100=X'
#  - 'FRA40=X'
#  - 'GER30=X'
#  - 'US30=X'
#  - 'NAS100=X'
#  - 'SPX500=X'
#  - 'BCHUSD=X'
#  - 'BTCUSD=X'
#  - 'ETHUSD=X'
#  - 'LTCUSD=X'
#  - 'XRPUSD=X'